version: "3.0"
services:
  mysql-db:
    image: mariadb:10.4
    restart: "always"
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "core"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "password"

  mq-service:
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: "test"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      
  api:
    build: .
    container_name: api
    tty: true
    command: yarn start
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ./:/usr/app
      - ./node_modules:/usr/app/node_modules
    depends_on:
      - mysql-db

volumes:
  mysql:
  rabbitmq-data: