version: "3.0"
services:
  mysql-db:
    image: mariadb:10.4
    restart: "always"
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "core"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "password"

  mq-service:
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: "test"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  mysql:
  rabbitmq-data: